---
defaults: &defaults
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true
  pool: 5

development:
  <<: *defaults
    
test:
  <<: *defaults

production:
  <<: *defaults

profiling:
  <<: *defaults

stage:
  <<: *defaults
