---
defaults: &defaults
  delivery_method: :smtp
  smtp_settings:
    enable_starttls_auto: true
    address: <%= ENV['MAIL_HOST'] %>
    port: 587
    domain: <%= ENV['MAIL_DOMAIN'] %>
    authentication: :plain
    user_name: <%= ENV['MAIL_USER'] %>
    password: <%= ENV['MAIL_PWD'] %>

development:
  <<: *defaults
    
test:
  <<: *defaults

production:
  <<: *defaults

profiling:
  <<: *defaults

stage:
  <<: *defaults
